      PROGRAM QUADPLEH
      USE data_mod
      USE io_mod
      USE assembly_mod
      USE solver_mod
!
!  THIS IS A B.E. PROGRAM THAT USES (QUA)DRATIC ELEMENTS FOR THE
!  SOLUTION OF (D)YNAMIC PLANE (E)LASTIC OR VISCOELASTIC TIME
!  (H)ARMONIC PROBLEMS
!
!  PROGRAM NO. 4
!
!  SET MAXIMUM DIMENSIONS
!  NNE= MAXIMUM NUMBER OF ELEMENTS
!  NX=  MAXIMUM DIMENSION OF THE SYSTEM OF EQUATIONS 
!  NX=  2*MAXIMUM NUMBER OF NODES= 4*MAXIMUM NUMBER OF ELEMENTS
!  NX1= 3*MAXIMUM NUMBER OF NODES= 6*MAXIMUM NUMBER OF ELEMENTS
!  NPM=MAXIMUM NUMBER OF INTERNAL POINTS
!  NFM=MAXIMUM NUMBER OF FREQUENCIES
!
!
      CHARACTER*12 FILEIN,FILEOUT,FILEISD
      CHARACTER*80 TITLE
      INTEGER :: NNE, NX, NX1, NPM, NFM, I, J, NN
      REAL :: RGE, DAM

!

!       COMMON/MATG/ G
!       COMMON/MATH/ H
!       COMMON N,L,CP,CS,GE,RO,XNU,FR,INP,IPR
!
!  ASSIGN NUMBERS FOR INPUT AND OUTPUT FILES
!
      INP=11
      IPR=12
      IPT=13
!
!  READ NAMES AND OPEN  FILES FOR INPUT AND OUTPUT
!
!     WRITE(*,' (A) ') ' NAME OF INPUT FILE (MAX. 12 CHART.)'
!      READ(*,'  (A) ')FILEIN
      FILEIN='squa4.dat'
      FILEOUT='squa4.out'
      FILEISD='disp.dat'      
      OPEN(INP,FILE=FILEIN,STATUS='OLD')
!      WRITE(*,' (A) ') ' NAME OF OUTPUT FILE (MAX. 12 CHART.)'
!      READ(*,' (A) ')FILEOUT
      OPEN(IPR,FILE=FILEOUT,STATUS='unknown')
      OPEN(ISD,FILE=FILEISD,STATUS='unknown')
!
!  READ DATA
!
      WRITE(IPR,100)
  100 FORMAT(' ',79('*'))
      READ(INP,'(A)') TITLE
      WRITE(IPR,'(A)') TITLE
      READ(INP,*) NE, L, NFR, RGE, DAM, RO, XNU
      GE=CMPLX(RGE,RGE*2.*DAM)
      CS=SQRT(GE/RO)
      CP=CS*SQRT((2.-2.*XNU)/(1.-2.*XNU))
      WRITE(IPR,300)NE,L,NFR,CP,CS,GE,DAM,RO,XNU
  300 FORMAT(//' DATA'//2X,'NUMBER OF BOUNDARY ELEMENTS =',I3/2X, &
     'NUMBER OF INTERNAL POINTS =',I3/2X, &
     'NUMBER OF FREQUENCIES =',I3/2X, &
     'P-WAVE VELOCITY=',G14.7,',',G14.7/2X, &
     'S-WAVE VELOCITY=',G14.7,',',G14.7/2X, &
     'SHEAR MODULUS=',G14.7,',',G14.7/2X, &
     'DAMPING RATIO=',G14.7/2X,'DENSITY=',G14.7/2X, &
     'POISSON RATIO=',G14.7)
      N = 2*NE
      NN = 2*N
      NX = NN
      NX1 = 3*N
      NPM = MAX(L, 1)
      NFM = MAX(NFR, 1)
      NNE = NE
      ALLOCATE(FI(NX), DFI(NX1), BC(NX1), G(NX,NX1), H(NX,NX), DSOL(2*NPM))
      ALLOCATE(X(2*NNE+1), Y(2*NNE+1), CX(NPM), CY(NPM))
      ALLOCATE(KODE(NX1), AFR(NFM))
      CALL INPUT_DATA()
      DO 60 I=1,NFR
      FR=AFR(I)
      DO 40 J=1,6*NE
   40 DFI(J)=BC(J)
!
!  COMPUTE G AND H MATRICES AND FORM SYSTEM (A X = F)
!

      CALL GHMAT4(X,Y,G,H,FI,DFI,KODE,NX,NX1)

!
!  SOLVE SYSTEM OF EQUATIONS
!
      CALL CSOLVER(H,FI,NN,NX)
!
!  COMPUTE STRESS AND DISPLACEMENT VALUES AT INTERNAL POINTS.
!
      CALL INTER4(FI,DFI,KODE,CX,CY,X,Y,DSOL)
!
!  PRINT RESULTS AT BOUNDARY NODES AND INTERNAL POINTS
!
      CALL OUTPUT4(X,Y,FI,DFI,CX,CY,DSOL)

      CALL SAVE_DISP(NODE,FI)
   60 CONTINUE
!
!   CLOSE INPUT AND OUTPUT FILES
!
      CLOSE (INP)
      CLOSE (IPR)
      CLOSE (ISD)
      STOP
      END
